/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminpanel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author Sagarchigni
 */
public class staffadd extends javax.swing.JDialog {

    /**
     * Creates new form staffadd
     */
    public staffadd(java.awt.Frame parent, boolean modal) {
        
        
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
    }
    public void insert()
    {
          String sid1=sid.getText();
        String suser1=suser.getText();
        String spass1=encryption(spass.getText());
        String semail1=semail.getText();
        String  scontactno1=scontact.getText();
        String saddress1=saddress.getText();
         //------------//
        SimpleDateFormat format = new SimpleDateFormat("yyyy-M-dd");
        Date d1 = new Date();
        String sdate = new String(format.format(d1));  
        //------------//
       

         try
            {
                
                String sgender="Male";
                if(female.isSelected())
                {
                    sgender="Female";
                }
                String sshift="Morning";
                if(day.isSelected())
                {
                    sshift="Day";
                }
              
                
                 Connection conn;
                 
               
                Class.forName("com.mysql.jdbc.Driver");
                String url="jdbc:mysql://localhost/staffdetails";
                conn=DriverManager.getConnection(url,"root","");
                PreparedStatement pstmt = conn.prepareStatement("INSERT INTO staffdet VALUES(?,?,?,?,?,?,?,?,?)");
        
                pstmt.setString(1,sid1);
                pstmt.setString(2,spass1);
                pstmt.setString(3,suser1);
                pstmt.setString(4,sgender);
                pstmt.setString(5,saddress1);
                pstmt.setString(6,scontactno1);
                pstmt.setString(7,semail1);
                pstmt.setString(8,sdate);
                pstmt.setString(9,sshift);
                
                pstmt.executeUpdate();                                               

                 JOptionPane.showMessageDialog(this, "You have Successfully Submitted Staff Details");
                 this.dispose();
                
              
            
            }
            catch(Exception e)
            {
                System.out.println(e);
                //e.printStackTrace();  
                validstaffid.setText("StaffID Already Exists use another!!");
               
               
            }

    }
      public static String encryption(String hashpass)
      {
          try
          {
             MessageDigest md=MessageDigest.getInstance("MD5");
             byte[] messageDigest=md.digest(hashpass.getBytes());
             BigInteger number=new BigInteger(1,messageDigest);
             String hashedpass=number.toString(16);
             while(hashedpass.length()<32)
             {
                 hashedpass="0"+hashedpass;
             }
             return hashedpass;
                 

          }
          catch(Exception e)
          {
              return "";
          }
          
      }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        male = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        spass = new javax.swing.JPasswordField();
        semail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        saddress = new javax.swing.JTextField();
        showpass = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        scontact = new javax.swing.JTextField();
        validuser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        suser = new javax.swing.JTextField();
        validstaffid = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        morning = new javax.swing.JRadioButton();
        day = new javax.swing.JRadioButton();
        add = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        validcontact = new javax.swing.JLabel();
        validpassword = new javax.swing.JLabel();
        validemail = new javax.swing.JLabel();
        validaddress = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        male.setBackground(new java.awt.Color(44, 102, 76));
        buttonGroup1.add(male);
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setSelected(true);
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 50, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 80, 20));

        spass.setBackground(new java.awt.Color(44, 102, 76));
        spass.setForeground(new java.awt.Color(255, 255, 255));
        spass.setBorder(null);
        spass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spassMouseClicked(evt);
            }
        });
        jPanel1.add(spass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 200, 20));

        semail.setBackground(new java.awt.Color(44, 102, 76));
        semail.setForeground(new java.awt.Color(255, 255, 255));
        semail.setBorder(null);
        semail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                semailMouseClicked(evt);
            }
        });
        jPanel1.add(semail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 200, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact no:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, 20));

        saddress.setBackground(new java.awt.Color(44, 102, 76));
        saddress.setForeground(new java.awt.Color(255, 255, 255));
        saddress.setBorder(null);
        saddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saddressMouseClicked(evt);
            }
        });
        jPanel1.add(saddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 200, 20));

        showpass.setBackground(new java.awt.Color(44, 102, 76));
        showpass.setForeground(new java.awt.Color(255, 255, 255));
        showpass.setText("Show Password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        jPanel1.add(showpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, 20));

        scontact.setBackground(new java.awt.Color(44, 102, 76));
        scontact.setForeground(new java.awt.Color(255, 255, 255));
        scontact.setBorder(null);
        scontact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scontactMouseClicked(evt);
            }
        });
        jPanel1.add(scontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 200, 20));

        validuser.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        validuser.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(validuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 200, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Staff Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, 20));

        suser.setBackground(new java.awt.Color(44, 102, 76));
        suser.setForeground(new java.awt.Color(255, 255, 255));
        suser.setBorder(null);
        suser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suserMouseClicked(evt);
            }
        });
        suser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suserActionPerformed(evt);
            }
        });
        jPanel1.add(suser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 200, 20));

        validstaffid.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        validstaffid.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(validstaffid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 200, 10));

        sid.setBackground(new java.awt.Color(44, 102, 76));
        sid.setForeground(new java.awt.Color(255, 255, 255));
        sid.setBorder(null);
        sid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidMouseClicked(evt);
            }
        });
        jPanel1.add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 200, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Staff-ID:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 90, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter Staff Information Below:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 330, 20));

        female.setBackground(new java.awt.Color(44, 102, 76));
        buttonGroup1.add(female);
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Shift:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, 20));

        morning.setBackground(new java.awt.Color(44, 102, 76));
        buttonGroup2.add(morning);
        morning.setForeground(new java.awt.Color(255, 255, 255));
        morning.setSelected(true);
        morning.setText("Morning");
        morning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morningActionPerformed(evt);
            }
        });
        jPanel1.add(morning, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, -1, -1));

        day.setBackground(new java.awt.Color(44, 102, 76));
        buttonGroup2.add(day);
        day.setForeground(new java.awt.Color(255, 255, 255));
        day.setText("Day");
        jPanel1.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, -1, -1));

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.setText("Add");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 570, 80, -1));

        Exit.setBackground(new java.awt.Color(255, 255, 255));
        Exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Exit.setText("Cancel");
        Exit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 80, -1));

        validcontact.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        validcontact.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(validcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 200, -1));

        validpassword.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        validpassword.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(validpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 200, 10));

        validemail.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        validemail.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(validemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 200, 10));

        validaddress.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        validaddress.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(validaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 200, 10));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 200, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 200, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 200, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 200, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 200, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 200, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminpanel/icons/dialogpanel_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 520, 670));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        // TODO add your handling code here:
        Exit.setBackground(Color.white);
        Exit.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_ExitMouseExited

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        // TODO add your handling code here:
        Exit.setBackground(new Color(13, 76, 51));
        Exit.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_ExitMouseEntered

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String sid1=sid.getText();
        String suser1=suser.getText();
        String spass1=encryption(spass.getText());
        String semail1=semail.getText();
        String  scontactno1=scontact.getText();
        String saddress1=saddress.getText();
        // String sdatechoser=((JTextField)datechoser.getDateEditor().getUiComponent()).getText();

        if(sid1.equals("") && suser1.equals("") && spass1.equals("") && scontactno1.equals("") && semail1.equals("") && saddress1.equals("") )
        {
            JOptionPane.showMessageDialog(this, "Please Enter Full Information!!!", "Error", JOptionPane.ERROR_MESSAGE);

        }
        else if(sid1.equals(""))
        {
            validstaffid.setText("Please Enter StaffID!!");

        }
        else if(suser1.equals(""))
        {
            validuser.setText("Please Enter Staff Name!!");

        }
        else if(spass1.equals(""))
        {
            validpassword.setText("Please Enter Password!!");
        }
        else if(semail1.equals(""))
        {
            validemail.setText("Please Enter Email!!!");
        }
        else if(scontactno1.equals(""))
        {
            validcontact.setText("Please Enter Contact No:!!");
        }
        else if(saddress1.equals(""))
        {
            validaddress.setText("Please Enter Address!!");
        }

        else if(sid1!=(null))
        {
            String PATTERNs="^[a-z0-9]{0,10}$";
            Pattern patts=Pattern.compile(PATTERNs);
            Matcher matchs=patts.matcher(sid.getText());
            if(!matchs.matches())
            {
                validstaffid.setText("Invalid staffID!!!");

            }
            else
            if(sid!=(null))
            {
                String PATTERNs1="^[a-z]{4}[0-9]{4}$";
                Pattern patts1=Pattern.compile(PATTERNs1);
                Matcher matchs1=patts1.matcher(sid.getText());
                if(!matchs1.matches())
                {
                    validstaffid.setText("Use Four alphabet with Four Digits !!!");

                }

                else
                {
                    if(suser1!=(null))
                    {
                        String PATTERNu="^[a-zA-Z]+(\\s[a-zA-Z]+)?$";
                        Pattern pattu=Pattern.compile(PATTERNu);
                        Matcher matchu=pattu.matcher(suser.getText());
                        if(!matchu.matches())
                        {
                            validuser.setText("Do not use number in Staff !!!");
                        }
                        else
                        {
                            if(spass1!=(null))
                            {
                                String PATTERNp="^[a-zA-Z0-9]{0,30}$";
                                Pattern pattp=Pattern.compile(PATTERNp);
                                Matcher matchp=pattp.matcher(spass.getText());
                                if(!matchp.matches())
                                {
                                    validpassword.setText("Unnecessary use of charachters!!!");
                                }
                                else
                                {
                                    if(semail1!=(null))
                                    {
                                        String PATTERNe="^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$";
                                        Pattern patte=Pattern.compile(PATTERNe);
                                        Matcher matche=patte.matcher(semail.getText());
                                        if(!matche.matches())
                                        {
                                            validemail.setText("Invalid Email!!!");
                                        }
                                        else
                                        {
                                            if(scontactno1!=(null))
                                            {
                                                String PATTERNc="^[0-9]{0,100}$";
                                                Pattern pattc=Pattern.compile(PATTERNc);
                                                Matcher matchc=pattc.matcher(scontact.getText());
                                                if(!matchc.matches())
                                                {
                                                    validcontact.setText("Please use number Only!!!");
                                                }
                                                else
                                                {
                                                    if(scontactno1!=(null))
                                                    {
                                                        String PATTERNc1="^[0-9]{10}$";
                                                        Pattern pattc1=Pattern.compile(PATTERNc1);
                                                        Matcher matchc1=pattc1.matcher(scontact.getText());
                                                        if(!matchc1.matches())
                                                        {
                                                            validcontact.setText("Contact Should use 10 digits only!!!");
                                                        }

                                                        else
                                                        {
                                                            if(saddress1!=(null))
                                                            {
                                                                String PATTERNa="^[a-zA-Z0-9,.!? ]*$";
                                                                Pattern patta=Pattern.compile(PATTERNa);
                                                                Matcher matcha=patta.matcher(saddress.getText());
                                                                if(!matcha.matches())
                                                                {
                                                                    validaddress.setText("Do not use number in address!!!");
                                                                }
                                                                else
                                                                {
                                                                    insert();
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }

                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_addActionPerformed

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        // TODO add your handling code here:
        add.setBackground(Color.white);
        add.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_addMouseExited

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        // TODO add your handling code here:
        add.setBackground(new Color(13, 76, 51));
        add.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_addMouseEntered

    private void morningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_morningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_morningActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        String gender="female";
    }//GEN-LAST:event_femaleActionPerformed

    private void sidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidMouseClicked
        // TODO add your handling code here:
        validstaffid.setText("");
    }//GEN-LAST:event_sidMouseClicked

    private void suserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suserActionPerformed

    private void suserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suserMouseClicked
        // TODO add your handling code here:
        validuser.setText("");
    }//GEN-LAST:event_suserMouseClicked

    private void scontactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scontactMouseClicked
        // TODO add your handling code here:
        validcontact.setText("");
    }//GEN-LAST:event_scontactMouseClicked

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        if(showpass.isSelected())
        {
            spass.setEchoChar((char)0);
        }
        else
        {
            spass.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassActionPerformed

    private void saddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saddressMouseClicked
        // TODO add your handling code here:
        validaddress.setText("");
    }//GEN-LAST:event_saddressMouseClicked

    private void semailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semailMouseClicked
        // TODO add your handling code here:
        validemail.setText("");
    }//GEN-LAST:event_semailMouseClicked

    private void spassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spassMouseClicked
        // TODO add your handling code here:
        validpassword.setText("");
    }//GEN-LAST:event_spassMouseClicked

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed

        String gender = "male";
    }//GEN-LAST:event_maleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staffadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staffadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staffadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staffadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                staffadd dialog = new staffadd(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton day;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton morning;
    private javax.swing.JTextField saddress;
    private javax.swing.JTextField scontact;
    private javax.swing.JTextField semail;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JTextField sid;
    private javax.swing.JPasswordField spass;
    private javax.swing.JTextField suser;
    private javax.swing.JLabel validaddress;
    private javax.swing.JLabel validcontact;
    private javax.swing.JLabel validemail;
    private javax.swing.JLabel validpassword;
    private javax.swing.JLabel validstaffid;
    private javax.swing.JLabel validuser;
    // End of variables declaration//GEN-END:variables
}
